DISTRO_NAME = "Kamol"
DISTRO_CODENAME = "master"
DISTRO_VERSION = "${DISTRO_CODENAME}-${DISTRO_NAME}"

PACKAGE_CLASSES = "package_rpm"

INIT_MANAGER = "sysvinit"

ENABLE_UART = "1"
LICENSE_FLAGS_ACCEPTED = "synaptics-killswitch"

IMAGE_INSTALL:append = " python3-flask nudoku helloworld nsnake"
RPI_USE_U_BOOT = "1"